### ISSUE TITLE
build: Failing NPM Publish workflow

### ISSUE THREAD

**Issue by davidtaing** [davidtaing/map-immute#2]
https://github.com/davidtaing/map-immute/actions/runs/4270017705/jobs/7433653970

```
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.NPM_AUTH_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'NPM_AUTH_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'Create Release Pull Request or Publish'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Create Release Pull Request or Publish
##[debug]Loading inputs
##[debug]Loading env
Run changesets/action@v1
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
No changesets found, attempting to publish any unpublished packages to npm
No user .npmrc file found, creating one
/home/runner/setup-pnpm/node_modules/.bin/pnpm release

> map-immute@0.2.1 release /home/runner/work/map-immute/map-immute
> pnpm build && changeset publish


> map-immute@0.2.1 build /home/runner/work/map-immute/map-immute
> tsup src/index.ts --format cjs,esm --dts

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.6.3
CLI Target: es2016
CJS Build start
ESM Build start
CJS dist/index.js 3.15 KB
CJS ⚡️ Build success in 26ms
ESM dist/index.mjs 2.16 KB
ESM ⚡️ Build success in 26ms
DTS Build start
DTS ⚡️ Build success in 961ms
DTS dist/index.d.ts 1.61 KB
🦋  info npm info map-immute
🦋  info map-immute is being published because our local version (0.2.1) has not been published on npm
🦋  info Publishing "map-immute" at "0.2.1"
🦋  error an error occurred while publishing map-immute: E404 Not Found - PUT https://registry.npmjs.org/map-immute - Not found 
🦋  error 
🦋  error  'map-immute@0.2.1' is not in this registry.
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error npm notice Publishing to https://registry.npmjs.org/
🦋  error npm ERR! code E404
🦋  error npm ERR! 404 Not Found - PUT https://registry.npmjs.org/map-immute - Not found
🦋  error npm ERR! 404 
🦋  error npm ERR! 404  'map-immute@0.2.1' is not in this registry.
🦋  error npm ERR! 404 
🦋  error npm ERR! 404 Note that you can also install from a
🦋  error npm ERR! 404 tarball, folder, http url, or git url.
🦋  error {
🦋  error   "error": {
🦋  error     "code": "E404",
🦋  error     "summary": "Not Found - PUT https://registry.npmjs.org/map-immute - Not found",
🦋  error     "detail": "\n 'map-immute@0.2.1' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
🦋  error   }
🦋  error }
🦋  error 
🦋  error npm ERR! A complete log of this run can be found in:
🦋  error npm ERR!     /home/runner/.npm/_logs/2023-02-25T12_52_12_150Z-debug-0.log
🦋  error 
🦋  error packages failed to publish:
🦋  map-immute@0.2.1
 ELIFECYCLE  Command failed with exit code 1.
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
    at m._setResult (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:7258)
    at m.CheckComplete (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:6686)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:5723)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]Set output published = false
##[debug]Set output publishedPackages = []
##[debug]Set output hasChangesets = false
##[debug]Finishing: Create Release Pull Request or Publish
```

**Comment by davidtaing** [comment]
Fixed this by changing the `NPM_TOKEN` to an automation token (does not require 2FA).

But this honestly could have been caused by anything else, such as invalid GitHub Action permissions, invalid `package.lock` settings, etc.
